"""Tag system for flashcard management and organization."""

import json
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class TagConfig:
    """Configuration for tag system."""

    default_tags: dict[str, str] = field(default_factory=dict)  # tag_name: description
    verification_tags: list[str] = field(
        default_factory=lambda: ["ai_verified", "ai_needs_review"]
    )
    generation_source_tags: list[str] = field(
        default_factory=lambda: ["ai_from_text", "ai_from_image", "ai_multi_type"]
    )
    hierarchy_tags: list[str] = field(
        default_factory=lambda: ["ai_parent_card", "ai_generated", "ai_variant"]
    )


class TagManager:
    """Manages tag system for AI-generated cards."""

    def __init__(self, config_dir: Path):
        self.config_dir = config_dir
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.config_file = self.config_dir / "tags.json"
        self.config = self._load_config()

    def _load_config(self) -> TagConfig:
        """Load tag configuration from file."""
        if self.config_file.exists():
            try:
                with open(self.config_file, encoding="utf-8") as f:
                    data = json.load(f)
                    return TagConfig(
                        default_tags=data.get("default_tags", {}),
                        verification_tags=data.get("verification_tags", []),
                        generation_source_tags=data.get("generation_source_tags", []),
                        hierarchy_tags=data.get("hierarchy_tags", []),
                    )
            except Exception as e:
                print(f"Error loading tag config: {e}")

        # Return default config
        return TagConfig(
            default_tags={
                "ai_verified": "Card verified by AI and meets best practices",
                "ai_needs_review": "Card generated by AI, pending manual review",
                "ai_from_text": "Card generated from text input",
                "ai_from_pdf": "Card generated from PDF document",
                "ai_from_slide": "Card generated from presentation slide",
                "ai_from_screenshot": "Card generated from screenshot",
                "ai_multi_type": "Generated as part of multi-type set",
                "ai_single_info": "Follows single information principle",
                "ai_parent_card": "This is a parent card with generated children",
                "ai_generated": "Generated by AI from another card or content",
                "ai_variant": "A variant of another card (different angle/type)",
            },
            verification_tags=["ai_verified", "ai_needs_review"],
            generation_source_tags=[
                "ai_from_text",
                "ai_from_pdf",
                "ai_from_slide",
                "ai_from_screenshot",
            ],
            hierarchy_tags=["ai_parent_card", "ai_generated", "ai_variant"],
        )

    def _save_config(self) -> None:
        """Save tag configuration to file."""
        try:
            with open(self.config_file, "w", encoding="utf-8") as f:
                json.dump(
                    {
                        "default_tags": self.config.default_tags,
                        "verification_tags": self.config.verification_tags,
                        "generation_source_tags": self.config.generation_source_tags,
                        "hierarchy_tags": self.config.hierarchy_tags,
                    },
                    f,
                    indent=2,
                    ensure_ascii=False,
                )
        except Exception as e:
            print(f"Error saving tag config: {e}")

    def get_verification_tags(self, is_verified: bool = False) -> list[str]:
        """Get appropriate verification tags."""
        if is_verified:
            return ["ai_verified", "ai_single_info"]
        return ["ai_needs_review"]

    def is_ai_verified(self, note_tags: list[str]) -> bool:
        """True when this note is already tagged as AI-verified."""
        return "ai_verified" in note_tags

    def tags_removed_when_resetting_ai_verification(self) -> list[str]:
        """Tags stripped by Clear AI verification markers (allows re-running verify)."""
        return ["ai_verified", "ai_single_info"]

    def get_generation_tags(
        self, source_type: str, is_verified: bool = False, is_variant: bool = False
    ) -> list[str]:
        """Get generation tags for a card (backward compatibility method)."""
        return self.get_complete_tags_for_generated_card(
            source_type, is_verified, is_variant
        )

    def get_source_tag(self, source_type: str) -> str | None:
        """Get source tag based on source type."""
        mapping = {
            "text": "ai_from_text",
            "pdf": "ai_from_pdf",
            "slide": "ai_from_slide",
            "screenshot": "ai_from_screenshot",
            "image": "ai_from_screenshot",
        }
        return mapping.get(source_type.lower())

    def get_hierarchy_tags_for_generated(self, is_variant: bool = False) -> list[str]:
        """Get hierarchy tags for a generated card."""
        tags = ["ai_generated"]
        if is_variant:
            tags.append("ai_variant")
        return tags

    def get_hierarchy_tags_for_parent(self) -> list[str]:
        """Get hierarchy tags for a parent card."""
        return ["ai_parent_card", "ai_generated"]

    def get_complete_tags_for_generated_card(
        self,
        source_type: str,
        is_verified: bool = False,
        is_variant: bool = False,
    ) -> list[str]:
        """Get a complete set of tags for a generated card."""
        tags = []

        # Add source tag
        source_tag = self.get_source_tag(source_type)
        if source_tag:
            tags.append(source_tag)

        # Add verification tag
        tags.extend(self.get_verification_tags(is_verified))

        # Add hierarchy tags
        tags.extend(self.get_hierarchy_tags_for_generated(is_variant))

        # Add single info tag
        tags.append("ai_single_info")

        return tags

    def get_tag_description(self, tag: str) -> str:
        """Get human-readable description of a tag."""
        return self.config.default_tags.get(tag, f"Custom tag: {tag}")

    def add_custom_tag(self, tag_name: str, description: str) -> None:
        """Add a custom tag to the system."""
        self.config.default_tags[tag_name] = description
        self._save_config()

    def get_all_ai_tags(self) -> list[str]:
        """Get all AI-related tags."""
        tags = list(self.config.default_tags.keys())
        return [t for t in tags if t.startswith("ai_")]

    def filter_ai_generated_cards_from_tags(self, tags: list[str]) -> bool:
        """Check if card tags indicate it's AI-generated."""
        ai_generated_indicators = {
            "ai_generated",
            "ai_from_text",
            "ai_from_pdf",
            "ai_from_slide",
            "ai_from_screenshot",
            "ai_multi_type",
            "ai_variant",
        }
        return bool(set(tags) & ai_generated_indicators)

    def is_manual_card(self, tags: list[str]) -> bool:
        """Check if a card is likely manually created (not AI-generated)."""
        return not self.filter_ai_generated_cards_from_tags(tags)


class DeckTagStrategy:
    """Strategy for assigning tags based on deck structure."""

    @staticmethod
    def get_deck_specific_tags(deck_name: str) -> list[str]:
        """Get tags specific to a deck (e.g., subject matter)."""
        # Parse deck name for potential tags
        # Format could be: "Main::Subject::Topic"

        parts = deck_name.split("::")
        tags = []

        if len(parts) > 1:
            # Add subject tag
            subject = parts[1].lower().replace(" ", "_")
            tags.append(f"subject_{subject}")

        if len(parts) > 2:
            # Add topic tag
            topic = parts[2].lower().replace(" ", "_")
            tags.append(f"topic_{topic}")

        return tags

    @staticmethod
    def get_recommended_tags_for_card(
        card_front: str, card_back: str, deck_name: str
    ) -> list[str]:
        """Get recommended tags based on card content and deck."""
        tags = DeckTagStrategy.get_deck_specific_tags(deck_name)

        # Add difficulty estimation tags
        back_length = len(card_back.split())
        if back_length < 10:
            tags.append("difficulty_easy")
        elif back_length < 30:
            tags.append("difficulty_medium")
        else:
            tags.append("difficulty_hard")

        return tags
